# Generated by Django 3.1.1 on 2023-12-22 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20231219_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('available_seats', models.PositiveIntegerField()),
                ('reserved_seats', models.PositiveIntegerField(default=0)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_seats_reserved', models.PositiveIntegerField()),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation_date_time', models.DateTimeField(auto_now_add=True)),
                ('bus_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.busschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
