# Generated by Django 3.1.1 on 2023-12-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20231228_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.IntegerField(default=36529, primary_key=True, serialize=False),
        ),
    ]
